version: "3.8"
services:
  mongo:
    image: mongo:5.0.2
    container_name: mongo
    hostname: mongo
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_DB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_DB_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_DB_DATABASE
      # - MONGO_DB_USERNAME=$MONGO_DB_USERNAME
      # - MONGO_DB_PASSWORD=$MONGO_DB_PASSWORD
    volumes:
       - db:/data/db
    networks:
      - main-network
    command: ["--bind_ip", "0.0.0.0"]
    
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: moviest-backend-api
    container_name: moviest-backend
    restart: on-failure
    depends_on:
      - mongo
    ports:
      - 8000:8000
    environment:
      - SERVER_PORT=8000
      - SPRING_DATA_MONGODB_HOST=localhost
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_USERNAME=$MONGO_USER
      - SPRING_DATA_MONGODB_PASSWORD=$MONGO_PASSWORD
      - SPRING_DATA_MONGODB_DATABASE=$MONGO_DATABASE
    networks:
      - main-network

networks:
  main-network:
    external:
      name: $NETWORK_NAME