# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Docker images for both frontend and backend

on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build Spring Boot backend
        uses: actions/checkout@v2
        with:
          context: ./movieist-api

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

        
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: paularinze/movieist-backend
          tags: 1.0
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # - name: Upload artifact for deployment job
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: java-app
      #     path: '${{ github.workspace }}/target/*.jar'

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          context: ./movieist-api
      - name: Install dependencies
        run: |
          npm install
        # build and test the apps
      - name: build
        run: |
          npm run build
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: paularinze/movieist-frontend
          tags: 1.0

 
