name: build Front End

on:
  # push:
  #   branches: 
  #     - master
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./moviest-frontend
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: |
        npm install
      # build and test the apps
    - name: build
      run: |
        npm run build
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push frontend image
      uses: docker/build-push-action@v2
      with:
        context: ./moviest-frontend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/moviest-frontend:1.0
    
    # - name: Build & push Docker image
    #   uses: mr-smithers-excellent/docker-build-push@v5
    #   with:
    #     context: ./moviest-frontend
    #     file: ./moviest-frontend/Dockerfile
    #     image: paularinze/moviest-frontend
    #     tags: 1.0
    #     registry: docker.io
    #     # dockerfile: Dockerfile
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
   